[package]
edition = "2024"
name = "oxhidifi"
version = "0.1.0"

[dependencies]
anyhow = "1.0.100"
async-channel = "2.5.0"
async-trait = "0.1.89"
cpal = "0.16.0"
crossbeam-channel = "0.5.15"
libadwaita = { version = "0.8.1", features = [
  "gio_v2_80",
  "gtk_v4_20",
  "v1_8",
] }
lofty = "0.22.4"
notify = "8.2.0"
parking_lot = "0.12.5"
regex = "1.12.2"
rtrb = "0.3.2"
rubato = "0.16.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "sqlite"] }
symphonia = { version = "0.5.5", features = ["all"] }
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["full"] }
tracing = "0.1.43"
tracing-subscriber = "0.3.22"

[dev-dependencies]
criterion = "0.8.0"

[[bench]]
harness = false
name = "bench_main"
